module Constants

  DEFAULT_TWEETS_PAR = 10
  SEARCH_TWEETS_PAR = 10
  COMMENT_TWEETS_PAR = 2

  SEARCH_USERS_PAR = 3
  LIKE_USERS_PAR = 5
  RECOMMEND_USER_AMOUNT = 5

  MAX_LENGTH_TWEET = 140

  MAX_IMAGE_HEIGHT_PIXELS = 800
  MAX_IMAGE_WIDTH_PIXELS = 800

  THUMB_IMAGE_HEIGHT_PIXELS = 80
  THUMB_IMAGE_WIDTH_PIXELS = 80

  MIN_IMAGE_HEIGHT_PIXELS = 200
  MIN_IMAGE_WIDTH_PIXELS = 200

end
